Repository googleapis/java-phishingprotection, pull requests merged in 2020-09, with the labels that each got.

#206 chore: regenerate README
  README.md
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: none

#208 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#222 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#224 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: phishingprotection, automerge, cla: yes

#226 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#231 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#233 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
