Repository googleapis/java-phishingprotection, pull requests merged in 2020-06, with the labels that each got.

#143 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#144 chore: regenerate with updated protoc
  proto-google-cloud-phishingprotection-v1beta1/src/main/java/com/google/phishingprotection/v1beta1/ReportPhishingRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#150 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#155 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#156 fix: migrate phishingprotection/v1beta1 to grpc_service_config
  google-cloud-phishingprotection/src/main/java/com/google/cloud/phishingprotection/v1beta1/stub/PhishingProtectionServiceV1Beta1StubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#160 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#164 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#165 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-phishingprotection/pom.xml
  grpc-google-cloud-phishingprotection-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-phishingprotection-v1beta1/pom.xml
Labels: cla: yes

#177 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
