Repository googleapis/java-phishingprotection, pull requests merged in 2021-05, with the labels that each got.

#432 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: phishingprotection, automerge, cla: yes

#433 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: none

#434 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#436 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes

#441 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes

#442 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#444 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes

#445 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#446 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#450 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full

#453 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: phishingprotection, automerge, cla: yes
